"use client";

import Link from "next/link";
import { use, useEffect, useState } from "react";
import { api } from "@/lib/api";
import type { CapaDraft, InspectionReport } from "@/lib/types";

export default function ReviewPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params);
  const [report, setReport] = useState<InspectionReport | null>(null);
  const [capa, setCapa] = useState<CapaDraft | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    api.getReport(id).then(setReport).catch((e) => setError(String(e)));
  }, [id]);

  async function run<T>(fn: () => Promise<T>, onOk: (v: T) => void) {
    setBusy(true);
    setError(null);
    try {
      onOk(await fn());
    } catch (e) {
      setError(String(e));
    } finally {
      setBusy(false);
    }
  }

  const g = (report?.general ?? {}) as Record<string, string>;

  return (
    <>
      <p>
        <Link href="/">← all reports</Link>
      </p>
      {error && <p className="err">{error}</p>}

      {report && (
        <div className="card">
          <h2>Inspection report {String(report.report_id)}</h2>
          <div className="kv">
            <span className="k">Overall result</span>
            <span>
              <span className={`badge ${String(report.overall_result)}`}>
                {String(report.overall_result)}
              </span>
            </span>
            <span className="k">Fail / pending code</span>
            <span>{(report.fail_code as string) ?? "—"}</span>
            <span className="k">Reason</span>
            <span>{(report.fail_reason as string) ?? "—"}</span>
            <span className="k">Vendor / factory</span>
            <span>{g.vendor_supplier_name ?? "—"}</span>
            <span className="k">Retail market</span>
            <span>{g.retail_market ?? "—"}</span>
            <span className="k">Protocol</span>
            <span>{g.protocol_no ?? "—"}</span>
          </div>
          {!capa && (
            <div className="row" style={{ marginTop: 14 }}>
              <button
                className="primary"
                disabled={busy}
                onClick={() => run(() => api.draft(id), setCapa)}
              >
                {busy ? "Drafting…" : "Generate draft CAPA"}
              </button>
              <span className="muted">
                Runs classify → retrieve → assemble → generate → guardrails.
              </span>
            </div>
          )}
        </div>
      )}

      {capa && <CapaView capa={capa} busy={busy} run={run} setCapa={setCapa} />}
    </>
  );
}

function CapaView({
  capa,
  busy,
  run,
  setCapa,
}: {
  capa: CapaDraft;
  busy: boolean;
  run: <T>(fn: () => Promise<T>, onOk: (v: T) => void) => void;
  setCapa: (c: CapaDraft) => void;
}) {
  return (
    <div className="card">
      <div className="row" style={{ justifyContent: "space-between" }}>
        <h2>CAPA draft {capa.id}</h2>
        <span className={`badge ${capa.status}`}>{capa.status}</span>
      </div>

      <div className="kv">
        <span className="k">Failure type</span>
        <span>{capa.failure_type}</span>
        <span className="k">Generated by</span>
        <span>{capa.generated_by}</span>
        <span className="k">Confidence</span>
        <span>{capa.confidence.toFixed(2)}</span>
      </div>

      <p style={{ marginTop: 14 }}>
        <strong>Root cause.</strong> {capa.root_cause}
      </p>
      <p>
        <strong>Containment.</strong> {capa.containment}
      </p>

      <h2 style={{ marginTop: 14 }}>Corrective actions</h2>
      {capa.corrective_actions.map((a) => (
        <div className="action" key={a.step}>
          <div>
            {a.step}. {a.description}
          </div>
          <div className="cite">
            cite: {a.citation}
            {a.owner ? ` · owner: ${a.owner}` : ""}
          </div>
        </div>
      ))}

      <p style={{ marginTop: 12 }}>
        <strong>Verification.</strong> {capa.verification_method}
      </p>

      {capa.guardrail_flags.length > 0 && (
        <div style={{ marginTop: 12 }}>
          <h2>Guardrail flags</h2>
          {capa.guardrail_flags.map((f, i) => (
            <div className="flag" key={i}>
              ⚑ {f}
            </div>
          ))}
        </div>
      )}

      <div className="row" style={{ marginTop: 16 }}>
        {(capa.status === "draft" || capa.status === "escalated") && (
          <>
            <button
              className="primary"
              disabled={busy || capa.status === "escalated"}
              title={capa.status === "escalated" ? "Escalated — routed off the GenAI path" : ""}
              onClick={() => run(() => api.approve(capa.id), setCapa)}
            >
              Approve (HITL #1)
            </button>
            <button disabled={busy} onClick={() => run(() => api.reject(capa.id), setCapa)}>
              Reject
            </button>
          </>
        )}
        {capa.status === "vendor_implementing" && (
          <button
            disabled={busy}
            onClick={() => run(() => api.submitEvidence(capa.id), setCapa)}
          >
            Submit vendor evidence
          </button>
        )}
        {capa.status === "verifying" && (
          <>
            <button
              className="primary"
              disabled={busy}
              onClick={() => run(() => api.verify(capa.id, true), setCapa)}
            >
              Verify pass → close (HITL #2)
            </button>
            <button disabled={busy} onClick={() => run(() => api.verify(capa.id, false), setCapa)}>
              Verify fail → rework
            </button>
          </>
        )}
        {capa.status === "closed" && <span className="muted">Closed & written back.</span>}
      </div>
    </div>
  );
}
